CI setup
Nitrokey/solo2 pull request #5
Opened 2021-06-03 10:02 UTC by LennardBoediger

all test passed

2021-06-03 10:13 UTC, LennardBoediger commented
ready to merge

2021-06-11 13:42 UTC, robin-nitrokey commented on .gitlab-ci.yml
> +    - cp ./runners/lpc55/firmware-*.bin artifacts
Can we `mkdir -p artifacts` instead of adding `artifacts/.keep` to version control?

2021-06-11 16:23 UTC, robin-nitrokey commented
[Merging the `make` steps into a single job](https://github.com/Nitrokey/solo2/commit/67f5237bd5d84590c1c44e2ec0637ecac2e0c098) (per board) reduces the execution time by half.  Caching `runners/lpc55/target` and `$CARGO_HOME` = `/usr/local/cargo` should further speed up the process, but I didn’t manage to set that up.

2021-06-15 12:22 UTC, LennardBoediger commented
> [Merging the `make` steps into a single job](https://github.com/Nitrokey/solo2/commit/67f5237bd5d84590c1c44e2ec0637ecac2e0c098) (per board) reduces the execution time by half. Caching `runners/lpc55/target` and `$CARGO_HOME` = `/usr/local/cargo` should further speed up the process, but I didn’t manage to set that up. Alternatively, [running them sequentially](https://github.com/Nitrokey/solo2/commit/fa3b2f7fa17d7c7258bc2e2e73c4484d2ea8c9fc) speeds up the process slightly too.

Sequential jobs were turned off for troubleshooting reasons. 
I turned it back on, the resulting build time for 6 separate jobs is 02:42. (https://git.dotplex.com/nitrokey/solo2/-/pipelines/13225)
So it's just as fast as #fa3b2f7f, but allows a clean overview of which builds were successful

2021-06-15 19:17 UTC, LennardBoediger commented on .gitlab-ci.yml
> +    - cp ./runners/lpc55/firmware-*.bin artifacts
done

2021-06-24 10:10 UTC, LennardBoediger commented
all test passed
pull: https://git.dotplex.com/nitrokey/solo2/-/pipelines/13507
build: https://git.dotplex.com/nitrokey/solo2/-/pipelines/13509
Nighly: https://git.dotplex.com/nitrokey/solo2/-/pipelines/13510

2021-07-01 17:41 UTC, szszszsz requested changes
1. Please make it working locally
2. Would be nice to have a single `CI` recipe, which would be called by the CI, and would allow to test the execution locally without looking into the yaml file

2021-07-01 17:42 UTC, szszszsz commented
My output while running locally:
```
$ make -f docker-Makefile docker-build BOARD=nk3xn 
docker run -i --rm -v work/solo2:/app nitrokey3 make -C runners/lpc55 build BOARD=nk3xn           
make: *** runners/lpc55: No such file or directory.  Stop.                                              
make: *** [docker-Makefile:7: docker-build] Error 2                                                     
```

2021-07-04 20:56 UTC, LennardBoediger commented
it works locally for me.
created CI recipe in the Makefile

2021-07-05 16:27 UTC, szszszsz approved these changes
LGTM!

2021-07-05 16:31 UTC, closed without merging

2021-07-06 09:46 UTC, szszszsz commented
Merged! I have changed the commit message hence it is not recognized by Github as so, thus the "closed" message.